### ISSUE TITLE
Wrong condition in the assert

### ISSUE THREAD

**Issue by artemkomyshan** [akrzemi1/static_string#9]
https://github.com/akrzemi1/static_string/blob/cf952d9852083eb608e20bd4ae525fc2822c4304/include/ak_toolkit/static_string.hpp#L239

We can not access the last element by using operator[], because of the wrong condition in the assertion.

constexpr char operator[] (int i) const { return AK_TOOLKIT_ASSERT(i >= 0 && i < N), _array[i]; }
=>
constexpr char operator[] (int i) const { return AK_TOOLKIT_ASSERT(i >= 0 && i <= N), _array[i]; }

**Comment by akrzemi1** [comment]
This is intentional. the trailing `'\0'` at index `N` is not part of the value of the string.

**Comment by TreenProt** [comment]
the trailing '\0' at index N + 1

https://github.com/akrzemi1/static_string/blob/cf952d9852083eb608e20bd4ae525fc2822c4304/include/ak_toolkit/static_string.hpp#L198

**Comment by artemkomyshan** [comment]
Sorry for stilling your time.
